### ISSUE TITLE
Constants should be moved to .env file.

### ISSUE THREAD

**Issue by undercontr** [OnurSerbes/react-native-authentication#1]
Hi! congratulations on your library. I see you use API_KEY constant in auth.js file. Instead doing that you should place all your constants in ".env" file in your project root folder and access them by "process.env.API_KEY". 

Good luck!

**Comment by OnurSerbes** [comment]
Hi! Thanks for your comment, ı added the ".env" file with included it into ".gitignore". Instead of "process.env.API_KEY" ı wanted to import first and use it just like "API_KEY"
